config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get 'profile', to: 'users/registrations#show'
  end
  resources :posts do
    resources :comments, only: %i[create destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new(role: 'guest')
    case user.role
    when 'admin'
      can :manage, :all
    when 'user'
      can :create, :all
      can :read, :all
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
    when 'banned'
      cannot :read, :all
    else
      can :read, :all
      can :create, User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_presence_of :body
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  scope :reversed, -> { order('created_at DESC') }
  validates_presence_of :title, :body
  validates_uniqueness_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  ROLES = %i[user admin banned guest].freeze
  enum role: ROLES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.create(comment_params.merge(user: current_user))
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  respond_to :js, except: [:index]
  load_and_authorize_resource

  def index
    @posts = Post.reversed
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
  end

  def edit; end

  def update
    @post.update(post_params)
  end

  def destroy
    @post.destroy
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :authenticate_scope!
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /profile
  def show; end

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def resource_name
    :user
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name username last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name username last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_type(type)
    type == 'alert' ? 'danger' : 'success'
  end

  def title_type(resource)
    resource.persisted? ? 'Edit your post' : 'Create new post'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.comment.alert.alert-warning id="comment_#{comment.id}"
  - if can? :manage, comment
    = link_to post_comment_path(comment.post, comment), method: :delete, remote: true
      i.close ×
  span.comment-username = comment.user.username
  p = comment.body
  span.pull-right = time_ago_in_words(comment.created_at)

app/views/comments/_form.html.slim
= simple_form_for [ @post, @post.comments.build ], remote: true  do |f|
  .form-group
    = f.label :body, 'Leave your comment', class: 'label label-info'
    = f.error :body, class: 'text-danger'
    = f.input :body, class: 'form-control', error: false, label: false, autofocus: true
  = f.button :submit, remote: true

app/views/comments/create.js.erb
$('#comments').append('<%= j render @comment, comment: @comment %>');
$('#new_comment textarea').val('');
$('#post_<%= @comment.post.id %> .comment-field').html("<%= @comment.post.comments.count %> Comments")

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").slideUp('slow', function() { $(this).remove(); });
$('#post_<%= @comment.post.id %> .comment-field').html("<%= @comment.post.comments.count %> Comments")

app/views/layouts/application.html.slim
doctype html
html
  head
    title UserAuth
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    == render 'shared/navbar'
    == render 'shared/modal'
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{alert_type(name)} alert-dismissable", role: 'alert' do
          button.close type='button' data-dismiss='alert'
            span aria-hidden='true' &times;
            span.sr-only Close
          = msg
      = yield

app/views/persons/profile.html.slim
dl.dl-horizontal
  dt First name :
  dd = current_user.first_name
  dt Last name :
  dd = current_user.last_name
  dt Username :
  dd = current_user.username
  dt Email :
  dd = current_user.email
  p
    =link_to "Edit profile", edit_user_registration_path, class: 'btn btn-info'

app/views/posts/_form.html.slim
button.close.pull-right data-dismiss="modal" type="button"  ×
h2.h2.text-center = title_type(resource)
= simple_form_for resource, remote: true do |f|

  .form-group
    = f.label :title, class: 'label label-info'
    = f.error :title, class: 'text-danger'
    = f.input :title, class: 'form-control', error: false, label: false, autofocus: true
  .form-group
    = f.label :body, class: 'label label-info'
    = f.error :body, class: 'text-danger'
    = f.input :body, class: 'form-control', error: false, label: false

  .actions = f.button :submit, remote: true

app/views/posts/_post.html.slim
.panel.panel-default id="post_#{post.id}"
  .panel-heading
    = post.title
    .dropdown.pull-right
      a.fa.fa-bars.dropdown-toggle data-toggle="dropdown" href='#'
      ul.dropdown-menu
        li = link_to 'Show', post, remote: true,
                                   'data-target': '#myModal',
                                   'data-toggle': 'modal'
        - if can? :manage, post
          li = link_to 'Edit', edit_post_path(post), remote: true,
                                                     'data-target': '#myModal',
                                                     'data-toggle': 'modal'
          li = link_to 'Destroy', post, data: { confirm: 'Are you sure?' },
                                        method: :delete,
                                        remote: true
  .panel-body
    = post.body
    .text-right = "Author: #{post.user.username}"
    .text-right.comment-field = "#{post.comments.count} Comments"

app/views/posts/_show.html.slim
button.close.pull-right data-dismiss="modal" type="button"  ×
h2.h2.text-center Show
.panel-group
  == render post
#comments
  == render post.comments
- if can? :create, Comment
  == render 'comments/form'

app/views/posts/create.js.erb
$('.panel-group').append('<%= j render partial @post, locales: {post: @post} %>')
$('#new_post').remove();

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").slideUp('slow', function() { $(this).remove(); });

app/views/posts/edit.js.erb
$('.modal-body').html('<%= j render 'form', resource: @post %>');

app/views/posts/index.html.slim
h1 Listing posts

-if can? :create, Post
  = link_to fa_icon(:plus), new_post_path, id: 'new_post_link',
                                           class: 'new-post fa-2x',
                                           remote: true,
                                           'data-target': '#myModal',
                                           'data-toggle': 'modal'
.panel-group#posts
  ==render @posts

app/views/posts/new.js.erb
$('#new_post_link').after('<%== j render 'form' %>');

app/views/posts/show.js.erb
$('.modal-body').html('<%= j render 'show', post: @post %>')

app/views/posts/update.js.erb
<% if @post.errors.any? %>
  $('.modal-body').html('<%= j render 'form', resource: @post %>');
<% else %>
  $('#post_<%= @post.id %>').replaceWith('<%= j render @post, post: @post %>');
  $('.modal').modal('toggle');
<% end %>

app/views/shared/_modal.html.slim
#myModal.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      / .modal-header
      .modal-body

app/views/shared/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Blog', posts_url, class: 'navbar-brand'
      ul.nav.navbar-nav.navbar-left
        li = link_to 'Posts', posts_url
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li = link_to "Welcome #{current_user.email}", profile_path
          li = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          li = link_to 'Sign In', new_user_session_url
          li = link_to 'Sign Up', new_user_registration_url